# Generated by Django 4.0.3 on 2022-04-06 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_alter_client_timezone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='tag',
        ),
        migrations.AddField(
            model_name='client',
            name='prop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mailing.property'),
        ),
    ]
