# Generated by Django 4.0.3 on 2022-04-06 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0004_remove_client_tag_client_prop'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='prop',
            new_name='filter',
        ),
    ]
