# Generated by Django 4.0.3 on 2022-04-06 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0005_rename_prop_client_filter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tokens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(verbose_name='Start token')),
                ('end', models.DateTimeField(verbose_name='Stop token')),
                ('token', models.CharField(max_length=15, verbose_name='Token')),
            ],
        ),
    ]
