# Generated by Django 4.0.3 on 2022-04-06 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0006_tokens'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tokens',
        ),
    ]
