# Generated by Django 4.0.3 on 2022-04-08 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0007_delete_tokens'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='filter',
        ),
        migrations.AddField(
            model_name='client',
            name='tag',
            field=models.CharField(default='', max_length=15, verbose_name='Tag'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='filter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.client'),
        ),
        migrations.DeleteModel(
            name='Property',
        ),
    ]
