# Generated by Django 4.0.3 on 2022-04-08 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0008_remove_client_filter_client_tag_alter_mailing_filter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter', models.CharField(default='', max_length=15, verbose_name='Filter')),
            ],
        ),
        migrations.AlterField(
            model_name='client',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.filters'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='filter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.filters'),
        ),
    ]
