# Generated by Django 4.0.3 on 2022-04-08 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0009_filters_alter_client_tag_alter_mailing_filter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=12, unique=True, verbose_name='Phone'),
        ),
    ]
