# Generated by Django 4.0.3 on 2022-04-08 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0010_alter_client_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='stat',
            new_name='status',
        ),
    ]
